1.
Заголовок: Решение падает при невалидном количестве чисел
Severty: Medium
Priority: High
Возпроизводимость: всегда
Шаги для воспроизведения:
    1. Ввести число n невалидным. n должно быть в диапозоне [1, 300]
    2. Запустить исполнение функции
Фактический результат:
    1 - OK
    2 - NOK
Ожидаемый результат: выводится ошибка ValueError
FIX - нет проверки границ количества элементов в nums
      отлавливание этой ошибки представлено в burst_baloons/solution.py
      в функции _check_is_nums_count_is_valid

----------------------------------------------------------------------------------------------

2.
Заголовок: Решение падает при невалидном введенном числе
Severty: Medium
Priority: High
Возпроизводимость: всегда
Шаги для воспроизведения:
    1. Ввести число nums[i] невалидным. nums[i] должно быть в диапозоне [0, 100]
    2. Запустить исполнение функции
Фактический результат:
    1 - OK
    2 - NOK
Ожидаемый результат: выводится ошибка ValueError
FIX - нет проверки границ введенных чисел
      отлавливание этой ошибки представлено в burst_baloons/solution.py
      в функции _check_is_nums_are_valid

----------------------------------------------------------------------------------------------

3.
Заголовок: Решение падает, если в параметрах функции передан не List
Severty: Medium
Priority: High
Возпроизводимость: всегда
Шаги для воспроизведения:
    1. В параметрах функции ввести 1 вместо List
    2. Запустить исполнение функции
Фактический результат:
    1 - OK
    2 - NOK
Ожидаемый результат: выводится ошибка ValueError
FIX - нет проверки на тип, переданный в параметры функции
      отлавливание этой ошибки представлено в burst_baloons/solution.py
      в функции _check_is_list_of_nums

----------------------------------------------------------------------------------------------

4.
Заголовок: Решение падает, если в ввести не число в nums
Severty: Medium
Priority: High
Возпроизводимость: всегда
Шаги для воспроизведения:
    1. В списке nums ввести символ ['1']
    2. Запустить исполнение функции
Фактический результат:
    1 - OK
    2 - NOK
Ожидаемый результат: выводится ошибка ValueError
FIX - нет проверки типа введенного числа
      отлавливание этой ошибки представлено в burst_baloons/solution.py
      в функции _check_is_list_of_nums